# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: "3.6"
services:
  app:
    image: zsh-pazi-app-test
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
